# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='dated',
        ),
    ]
