# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20161220_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dated',
            field=models.DateField(),
        ),
    ]
